feat: rename CHAIN_NAMESPACE.Bitcoin -> CHAIN_NAMESPACE.UTXO
shapeshift/lib pull request #1006
Opened 2022-08-31 21:32 UTC by gomesalexandre

### Description

BREAKING CHANGE: CHAIN_NAMESPACE.Bitcoin is now CHAIN_NAMESPACE.UTXO

This renames CHAIN_NAMESPACE.Bitcoin to CHAIN_NAMESPACE.UTXO since it
now refers to any UTXO chain

2022-08-31 21:33 UTC, gomesalexandre commented
Current dependencies on/for this PR:
* main
  * **PR #1006** <a href="https://app.graphite.dev/github/pr/shapeshift/lib/1006" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #1007** <a href="https://app.graphite.dev/github/pr/shapeshift/lib/1007" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1008** <a href="https://app.graphite.dev/github/pr/shapeshift/lib/1008" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/lib/1006?utm_source=stack-comment).

2022-08-31 22:47 UTC, 0xApotheosis approved these changes
I like it, though I'd much prefer Pascal case rather than all-caps for acronyms, i.e. `Utxo`.

2022-09-01 20:53 UTC, 0xdef1cafe requested changes
the bike shed has been painted - `PascalCase` or ["upper camel case"](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case) for enum members per the rusty people

2022-09-01 21:20 UTC, 0xdef1cafe approved these changes

2022-09-01 22:08 UTC, 0xApotheosis commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/lib/1006?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: 3Gb5nbnZH8bmUx8G1ASR

2022-09-01 22:08 UTC, merged