chore: /lib in German - full update
shapeshift/lib pull request #1027
Opened 2022-09-15 21:15 UTC by thesmithdao

Weekly translation flow
Powered by Globalization Workstream

2022-09-17 23:13 UTC, thesmithdao commented
Closed by mistake. Reopen requested in Discord but also recording in Git :-)

2022-09-30 16:13 UTC, gomesalexandre requested changes
See comments

2022-09-30 16:29 UTC, firebomb1 approved these changes
Thanks for the review and changes.

2022-09-30 17:28 UTC, gomesalexandre approved these changes

2022-10-06 17:07 UTC, merged