feat(caip): add caip data for binance, kava, terra, secret
shapeshift/lib pull request #1033
Opened 2022-09-19 20:33 UTC by pastaghost

This adds CAIP data for Cosmos network assets {binance, kava, terra, secret}.

2022-09-19 21:23 UTC, 0xApotheosis requested changes

2022-09-19 21:23 UTC, 0xApotheosis commented on packages/caip/src/constants.ts
> +export const secretAsssetId: AssetId = 'cosmos:secret-4/slip44:529'
Too many s's in "asset".

2022-09-19 21:50 UTC, pastaghost commented on packages/caip/src/constants.ts
> +export const secretAsssetId: AssetId = 'cosmos:secret-4/slip44:529'
I was using snake case ;)

2022-09-20 00:32 UTC, 0xApotheosis commented on packages/caip/src/constants.ts
> +export const secretAsssetId: AssetId = 'cosmos:secret-4/slip44:529'
😁

2022-09-20 00:33 UTC, 0xApotheosis approved these changes
Now it's a little less slippery 🐍

2022-09-20 00:33 UTC, merged