feat(swapper): base unit vernacular
shapeshift/lib pull request #1122
Opened 2022-12-05 19:20 UTC by gomesalexandre

<h3 align="center">Description</h3>

<p align="center">
  <img src="https://media3.giphy.com/media/WZdlab0U3AkSc/200w.gif?cid=6c09b952rkl203f1mq7t5rs6nscwuz0razaq2kjjadpk286u&rid=200w.gif&ct=g">
</p>

Plumbing PR bringing the base unit vernacular in many places across lib, making sure we:

1. always name things the correct way, fixing some "precision" named vars that were actually base units
2. always use the vernacular, either for our in-house vars, or using destructuring to re-assign API-returned values to the right vernacular

Note that this is only property name changes (no runtime change), but will require web to accommodate for these (https://github.com/shapeshift/web/pull/3441 as a bigger boy, https://github.com/shapeshift/web/pull/3475 for the time being to make the diff less crazy on the former)

2022-12-05 19:21 UTC, gomesalexandre commented
Current dependencies on/for this PR:
* main
  * **PR #1122** <a href="https://app.graphite.dev/github/pr/shapeshift/lib/1122" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/lib/1122?utm_source=stack-comment).

2022-12-09 17:46 UTC, 0xApotheosis requested changes

2022-12-09 17:46 UTC, 0xApotheosis commented on packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
> +        gasPrice: '79036500000',
Do we want to do `gasPrice`, too?

2022-12-09 17:46 UTC, 0xApotheosis commented on packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
> +    sellAmountCryptoPrecision: '100000000',
This is not crypto precision, it's base unit.

2022-12-09 17:46 UTC, 0xApotheosis commented on packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
> +    buyAmountCryptoPrecision: '19136098853078932263', // 19.13 WETH
This is not crypto precision, it's base unit.

2022-12-09 17:46 UTC, 0xApotheosis commented on packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
> +    feeAmountInSellToken: '17238',
Do we want to name this properly too?

2022-12-09 17:46 UTC, 0xApotheosis commented on packages/swapper/src/swappers/cow/cowBuildTrade/cowBuildTrade.test.ts
> +    sellAmountWithoutFee: '99982762',
Do we want to name this properly too?

2022-12-12 00:41 UTC, gomesalexandre commented on packages/swapper/src/swappercli.ts
> +      sellAmountBeforeFeesCryptoBaseUnit: sellAmountBase,
Might as well

2022-12-12 00:44 UTC, gomesalexandre commented on packages/swapper/src/swappercli.ts
> +      sellAmountBeforeFeesCryptoBaseUnit: sellAmountBase,
652b55e5fd0953d8019fb33a5d411b789d482cb8

2022-12-12 00:45 UTC, gomesalexandre commented on packages/swapper/src/swappercli.ts
> -  const buyAmount = fromBaseUnit(quote.buyAmountCryptoPrecision || '0', buyAsset.precision)
What was named `buyAmountCryptoPrecision` was actually a base unit

2022-12-12 00:47 UTC, gomesalexandre commented on packages/swapper/src/swappers/cow/CowSwapper.test.ts
> +        sellAmountDeductFeeCryptoBaseUnit: '985442057341242012',
Little name change to make things clearer, does "without fee" means the base sell amount without fee deducted, or the base amount minus the fees deducted? Turns out it was the latter, so might as well rename it

2022-12-12 00:47 UTC, gomesalexandre commented on packages/swapper/src/swappers/cow/cowApprovalNeeded/cowApprovalNeeded.test.ts
> -        sellAmountCryptoPrecision: '10',
That was also a base unit

2022-12-20 23:49 UTC, 0xApotheosis approved these changes
LGTM ser 🐌

2022-12-20 23:51 UTC, merged