Swapper
shapeshift/lib pull request #39
Opened 2021-09-13 18:12 UTC by technojak

2021-09-16 20:15 UTC, bootsboogie approved these changes

2021-09-16 21:24 UTC, 0xdef1cafe commented on packages/swapper/src/manager/SwapperManager.test.ts
> +      expect(manager.getSwapper(SwapperType.Zrx)).toBeInstanceOf(ZrxSwapper)
```suggestion
      expect(manager.getSwapper(SwapperType.Zrx)).toBeInstanceOf(ZrxSwapper)
      expect(manager.getSwapper(SwapperType.Thorchain)).toBeInstanceOf(ThorchainSwapper)
```

2021-09-16 21:27 UTC, 0xdef1cafe requested changes

2021-09-16 21:27 UTC, 0xdef1cafe commented on packages/swapper/src/manager/SwapperManager.ts
> +export class SwapperManger<T extends SwapperType> {
```suggestion
export class SwapperManager<T extends SwapperType> {
```

2021-09-16 21:40 UTC, TrancelikeTechno commented on packages/swapper/src/manager/SwapperManager.ts
> +export class SwapperManger<T extends SwapperType> {
I spellz guud

2021-09-16 21:41 UTC, technojak commented on packages/swapper/src/manager/SwapperManager.ts
> +export class SwapperManger<T extends SwapperType> {
I spellz guud

2021-09-16 21:52 UTC, 0xdef1cafe approved these changes

2021-09-16 21:53 UTC, merged

2021-10-07 22:28 UTC, 0xdef1cafe commented
:tada: This PR is included in version @shapeshiftoss/swapper-v1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@shapeshiftoss/swapper/v/1.0.0)
- [GitHub release](https://github.com/shapeshift/lib/releases/tag/%40shapeshiftoss/swapper-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: