chore: add markdown links to asset descriptions
shapeshift/lib pull request #424
Opened 2022-03-08 20:08 UTC by willyogo

now that markdown links are supported, here are some markdown links

2022-03-10 22:36 UTC, 0xApotheosis approved these changes
Get it.

2022-03-15 23:49 UTC, 0xdef1cafe requested changes
can you change to all relative links please?

2022-03-16 15:42 UTC, willyogo commented
> can you change to all relative links please?

woo first time resolving conflicts, becoming more of an engineer every day. thanks for the patience @0xdef1cafe 🙏

2022-03-18 02:08 UTC, 0xdef1cafe approved these changes

2022-03-18 02:09 UTC, merged