Swapper get by pair
shapeshift/lib pull request #526
Opened 2022-04-15 00:54 UTC by DaoDev44

- Add `isSupportedAssets` to SwapperManager and `getSupportedAssts` to ZrxSwapper
- This is needed to chose swappers by assets instead of hard coding the swapper to use.

2022-04-15 12:15 UTC, chxash approved these changes
LGTM !

2022-04-15 12:15 UTC, chxash commented on packages/swapper/src/swappers/zrx/getZrxSupportedAssets/getZrxSupportedAssets.test.ts
> +    expect('yes').toEqual('yes')
Not sure about this, maybe a leftover ? :) even if its very basic we can unit test `getSupportedAssets` and `isSupportedAssets` methods

2022-04-17 23:38 UTC, elmutt commented on packages/swapper/src/swappers/zrx/getZrxSupportedAssets/getZrxSupportedAssets.ts
> +export function getZrxSupportedAssets(): CAIP19[] {
IMO this is fine for now and doesnt add much tech debt while its being decided

2022-04-17 23:38 UTC, elmutt approved these changes

2022-04-25 14:36 UTC, cjthompson commented on packages/swapper/src/api.ts
> +  isSupportedAssets(args: SupportedAssetInput): boolean
What does `supported` mean?

We talked about the possibility of an asset being available on only one side of a trade, like being a "sell" or "buy" asset but not both.

2022-04-25 14:39 UTC, cjthompson requested changes
I'd like to discuss `isSupportedAssets`

2022-04-27 16:59 UTC, cjthompson commented on packages/swapper/src/manager/SwapperManager.ts
> +   */
Remove?

2022-04-27 16:59 UTC, cjthompson commented on packages/swapper/src/manager/SwapperManager.ts
> +   *
Please add a description of the function here

2022-04-27 17:02 UTC, cjthompson approved these changes
I'd like to discuss `isSupportedAssets`

2022-04-27 18:03 UTC, merged