fix: @shapeshiftoss/types version references and tokens reference
shapeshift/lib pull request #585
Opened 2022-04-29 21:03 UTC by GMSteuart

- Reverts removal of the tokens reference
- Updates "@shapeshiftoss/types package references to 3.0

2022-04-29 21:37 UTC, GMSteuart commented
@0xdef1cafe please review

2022-04-29 22:18 UTC, GMSteuart commented
@cjthompson this will fix the typings problems occurring in build

2022-04-29 23:58 UTC, elmutt submitted a review, later dismissed

2022-04-29 23:58 UTC, elmutt commented
should get this merged soon for the tokens revert

2022-04-30 03:51 UTC, 0xApotheosis requested changes
Commit `yarn.lock` diff?

2022-04-30 04:24 UTC, GMSteuart commented
@0xApotheosis updated heres [yarn.lock](https://github.com/shapeshift/lib/pull/585/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de)

2022-04-30 05:13 UTC, 0xApotheosis commented
@GMSteuart merge conflict with `yarn.lock` - please merge in master, re-run `yarn`, then commit the resulting `yarn.lock`.

2022-04-30 05:40 UTC, 0xApotheosis approved these changes
Builds correctly.

2022-05-02 22:53 UTC, gomesalexandre reviewed
@GMSteuart Can you fix the conflict in `packages/chain-adapters/package.json` ? 🙏🏽 
Tested locally after mergefixing it and it builds fine. Will accept after the mergefix.

2022-05-03 13:22 UTC, GMSteuart commented
@gomesalexandre should be good to go. 🙂

2022-05-03 15:57 UTC, gomesalexandre approved these changes
Tested again locally and build still passes without errors.

2022-05-03 16:10 UTC, kaladinlight commented on yarn.lock
> +"@shapeshiftoss/types@^2.0.0":
It seems like there is a yarn lock issue related to this types package version. We are trying to reference version ^3.0.0 from `market-service`, but there is only one version reference of `2.11.0` in the yarn lock. I would expect a v2.xx version for something like `unchained-client` that hasn't been updated along with a v3.xx version for `market-service`

2022-05-03 16:12 UTC, kaladinlight commented on yarn.lock
> +"@shapeshiftoss/types@^2.0.0":
Disregard. Peer/Dev dependencies scenario...

2022-05-03 16:12 UTC, kaladinlight approved these changes

2022-05-03 22:47 UTC, theoboldfrazier approved these changes

2022-05-03 22:47 UTC, merged