Lib57 execute quote
shapeshift/lib pull request #87
Opened 2021-09-30 19:56 UTC by DaoDev44

- Add `executeQuote` to Swapper
- Add tests coverage.

closes #57

2021-10-01 22:46 UTC, 0xdef1cafe requested changes

2021-10-01 22:46 UTC, 0xdef1cafe commented on packages/swapper/src/api.ts
> +  buildQuoteTx(args: BuildQuoteTxInput): Promise<Quote | undefined>
```suggestion
  buildQuoteTx(args: BuildQuoteTxInput): Promise<Quote>
```

2021-10-01 22:46 UTC, 0xdef1cafe commented on packages/swapper/src/api.ts
> +  executeQuote(args: ExecQuoteInput): Promise<ExecQuoteOutput | undefined>
```suggestion
  executeQuote(args: ExecQuoteInput): Promise<ExecQuoteOutput>
```

2021-10-01 22:46 UTC, 0xdef1cafe commented on packages/swapper/src/swappers/thorchain/ThorchainSwapper.ts
> +    return undefined
```suggestion
    throw new Error('ThorchainSwapper: executeQuote unimplemented')
```

2021-10-01 22:48 UTC, toshiSat approved these changes

2021-10-04 17:04 UTC, 0xdef1cafe approved these changes

2021-10-04 17:04 UTC, merged