feat: replace '/api/v1/market' call with '/api/v1/quote' in getUsdRate
shapeshift/lib pull request #916
Opened 2022-07-28 13:26 UTC by chxash

This changes the endpoint used in `getUsdRate` method, because the one currently used has been deprecated.
I tested it in web, checked rates there and performed a swap.
closes https://github.com/shapeshift/lib/issues/759

Steps to test : 

- Link with web locally
- Start swap with ERC20 tokens (not ETH)
- Verify rates are consistent with current market
- Perform swap

2022-07-28 15:33 UTC, 0xdef1cafe requested changes
technically looks sounds, getting a lot of errors from the quote api - our standard UX is inputting values that cause errors, e.g.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/88504456/181578270-fb1efdbc-06f4-416f-aebc-3ab7a82ecd51.png">

we'll have to handle these error conditions more gracefully

2022-07-29 14:42 UTC, chxash commented
@0xdef1cafe I was finally able to reproduce this issue
This occurs in `getCowSwapTradeQuote.ts` (where `quote` api is already used) when `CowSwap` expects a fee greater than $10 (which is our minimum when lower value is provided by UX / the user).
This is only occurring with `quote` api when we are performing a `sell` operation, so the code in this PR where I am performing a `buy` is not at fault I think.

I have tried changing `getCowSwapMinMax.ts` logic in order to perform a quote/buy operation to retrieve a meaningful fee. But the fee can be very different for buy and sell operation.
So for now I only **increased our minimum value for `CowSwap` to $20** which should not bother the user too much given fees are commonly $1 - $10. Maybe we can create a separate issue to find a more robust way of estimating fee / calculating a minimum ?

2022-07-29 16:40 UTC, 0xdef1cafe commented
> @0xdef1cafe I was finally able to reproduce this issue This occurs in `getCowSwapTradeQuote.ts` (where `quote` api is already used) when `CowSwap` expects a fee greater than $10 (which is our minimum input value when lower value is provided by UX / the user). This is only occurring with `quote` api when we are performing a `sell` operation, so the code in this PR where I am performing a `buy` is not at fault I think.
> 
> I have tried changing `getCowSwapMinMax.ts` logic in order to perform a quote/buy operation to retrieve a meaningful fee. But the fee can be very different for buy and sell operation. So for now I only **increased our minimum value for `CowSwap` to $20** which should not bother the user too much given fees are commonly $1 - $10. Maybe we can create a separate issue to find a more robust way of estimating fee / calculating a minimum ?

@shapeshift/product FYI

2022-07-29 17:02 UTC, DiggyDiggy2 commented
Thanks! This sounds like a good approach. When I look at the trade activity from 0x there are only a few trades that are for very small amounts, and I'd assume those are our test trades. I think a $20 minimum is fine for cowswap.

2022-07-29 18:28 UTC, gomesalexandre reviewed
Conceptually ok with this one, discussing about a potential regression I've found before stamping it

2022-07-29 18:39 UTC, 0xdef1cafe commented
with a rebase and a link locally this is behaving fine, i'm conceptually ok too.

2022-07-29 19:03 UTC, gomesalexandre approved these changes
Tested and rates still LGTM.

Note that as part of this PR, it was found that inputting a value less than the minimum amount (10$ in develop, 20$ here) will not block the flow from being continued, and we will fall back to whichever is the minimum 

Develop:

![image](https://user-images.githubusercontent.com/17035424/181826949-cf5d2f85-1bc0-45cd-9d76-5819a67faa5d.png)
![image](https://user-images.githubusercontent.com/17035424/181826962-9ee95819-7589-4bb6-8e45-99cec5254c24.png)

This branch: 
![image](https://user-images.githubusercontent.com/17035424/181826985-d714a3bd-6b3b-4fab-82ea-2b988addd74b.png)
![image](https://user-images.githubusercontent.com/17035424/181827008-2da245c7-0dc2-4ab1-b960-86caea9eae50.png)

Thanks @chxash for testing this one out on develop as well and confirming the behavior. This is **not** a regression so:

🐄

2022-07-29 19:12 UTC, 0xdef1cafe approved these changes

2022-07-29 19:12 UTC, merged