added mappings and utils for mtpelerin ramp
shapeshift/lib pull request #984
Opened 2022-08-22 00:34 UTC by jmurphy5613

2022-08-22 08:36 UTC, gomesalexandre commented
@jmurphy5613 please use conventional commits for your PR title/commits: https://www.conventionalcommits.org/en/v1.0.0/
I've renamed the title of this one as an example.

2022-08-22 08:38 UTC, gomesalexandre reviewed
Comment

2022-08-22 08:38 UTC, gomesalexandre commented on packages/caip/src/adapters/mtpelerin/index.ts
> +} as Record<AssetId, string>
Can we update the PR description with a reference to the MtPelerin docs where these are defined?

2022-08-22 08:44 UTC, gomesalexandre requested changes

2022-08-22 08:44 UTC, gomesalexandre commented on packages/caip/src/adapters/mtpelerin/index.ts
> +export const AssetIdToMtPelerinTicker = (assetId: string) => AssetIdToMtPelerinTickerMap[assetId]
```suggestion
export const assetIdToMtPelerinTicker = (assetId: string) => AssetIdToMtPelerinTickerMap[assetId]
```

2022-08-22 08:44 UTC, gomesalexandre commented on packages/caip/src/adapters/mtpelerin/index.ts
> +export const MtPelerinTickerToAssetId = (ticker: string) => MtPelerinTickerToAssetIdMap[ticker]
```suggestion
export const mtPelerinTickerToAssetId = (ticker: string) => MtPelerinTickerToAssetIdMap[ticker]
```

2022-08-23 17:51 UTC, 0xdef1cafe commented
closing in favor of https://github.com/shapeshift/lib/pull/986

2022-08-23 17:51 UTC, closed without merging